### ISSUE TITLE
Multiple genres / subjects / contributors search

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#1320]
both the `genres.labels`, `concepts.label` and `contributors.agent.label` need to allow for multiple values.

After a few discussion's we have decided like the other filters, comma separated values would work for this. Values should be wrapped in `"`, and if the contain `"`, have those escaped.

e.g. 
* `"Watson, Jacqueline."`
* `"Watson, Jacqueline.","Wellcome Trust Centre for the History of Medicine at UCL.","University College, London."`
* `"Watson, \"Danger\", Jacqueline.","University College, London."`

**Comment by jamesgorrie** [comment]
Ping @jtweed

**Comment by jtweed** [comment]
Yep, agree with that ^

**Comment by taceybadgerbrook** [comment]
@jamesgorrie what do these multiple selections look like in conversion*? Do queries get lumped into page.query.query, are there new fields, do multiple selections get separated by commas, etc. 

The reason I ask is because I would like to be able to see how users are getting on with this new facility.
