### ISSUE TITLE
group searches by unique anonymous_id and unique query

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue#930]

**Comment by taceybadgerbrook** [comment]
Are we limited to defining sessions by anonymousId and unique query? Or can we use time outs as well?

**Comment by taceybadgerbrook** [comment]
And if the field query._queryType == undefined, what does that mean?

**Comment by taceybadgerbrook** [comment]
The start of a session is relatively easy to define as:

data.source == landing_page/discover_tag or unspecified 
and
event.keyword not Search landing or Search result selected
and
query.query is not blank
and
query.page == 1

The start of subsequent sessions needs to be defined by the time elapsed until the next timestamp >30 minutes because users may search using more than one tab, each one of which will begin with the same set of parameters.

**Comment by taceybadgerbrook** [comment]
This looks like it should be part of ticket [4112](https://github.com/wellcomecollection/platform/issues/4112#event-3958593799). which contains the answer to my question about duration.  

4112 has been closed, so we should close this, too. Or am I misinterpreting this?

**Comment by harrisonpim** [comment]
Yep, I think you're right @taceybadgerbrook, sorry for not getting to this earlier. I think this ticket refers to some analysis i did a few weeks ago and wasn't intended to translate into changes to the source data.
